const getParams = require('./index')
const assert = require('assert')

assert.deepEqual(getParams(function(){}), [])
assert.deepEqual(getParams(function(a){}), [{ param: 'a' }])
assert.deepEqual(getParams(function(a,b){}), [{ param: 'a' }, { param: 'b' }])
assert.deepEqual(getParams(function(a,/*bork*/b){}), [{ param: 'a' }, { param: 'b' }])
assert.deepEqual(getParams(function(a,/*bork*/b/*bork*/){}), [{ param: 'a' }, { param: 'b' }])
assert.deepEqual(getParams(function(a,b=true,c){}), [{ param: 'a' }, { param: 'b', default: 'true' }, { param: 'c' }])
assert.deepEqual(getParams(()=>{}), [])
assert.deepEqual(getParams(a=>{}), [{ param: 'a' }])
assert.deepEqual(getParams((a,b)=>{}), [{ param: 'a' }, { param: 'b' }])
assert.deepEqual(getParams((a,/*bork*/b)=>{}), [{ param: 'a' }, { param: 'b' }])
assert.deepEqual(getParams((a,/*bork*/b/*bork*/)=>{}), [{ param: 'a' }, { param: 'b' }])
assert.deepEqual(getParams((a,b=true,c)=>{}), [{ param: 'a' }, { param: 'b', default: 'true' }, { param: 'c' }])